/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.skycast.infrastructure.weatherbit


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param icon Icon code for forecast image display
 * @param code Weather Condition code
 * @param description Weather Condition description
 */
@Serializable
data class WeatherConditions (

    /* Icon code for forecast image display */
    @SerialName("icon")
    val icon: String? = null,

    /* Weather Condition code */
    @SerialName("code")
    val code: String? = null,

    /* Weather Condition description */
    @SerialName("description")
    val description: String? = null

)