/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.skycast.interfaces.weatherbit


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param count Count of found observations
 * @param `data` 
 */
@Serializable
data class CurrentObservations (

    /* Count of found observations */
    @SerialName("count")
    val count: Int? = null,

    @SerialName("data")
    val `data`: List<CurrentObservation>? = null

)